- name: Create App Application Machine
  hosts: localhost
  environment:
    GCP_AUTH_KIND: "{{gcp_auth_kind}}"
    GCP_SERVICE_ACCOUNT_FILE: "{{ gcp_service_account_file }}"
    GCP_SCOPES: "{{gcp_scopes}}"

  tasks:
    # Add firewall rules for http
    - name: "Create http firewall rule"
      google.cloud.gcp_compute_firewall:
        name: "default-allow-http"
        allowed:
          - ip_protocol: tcp
            ports: ["80"]
        state: "present"
        source_ranges: ["0.0.0.0/0"]
        target_tags: ["http-server"]
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_service_account_file }}"
      when: cluster_state == "present"

    # Add firewall rules for https
    - name: "Create https firewall rule"
      google.cloud.gcp_compute_firewall:
        name: "default-allow-https"
        allowed:
          - ip_protocol: tcp
            ports: ["443"]
        state: "present"
        source_ranges: ["0.0.0.0/0"]
        target_tags: ["http-server"]
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_service_account_file }}"
      when: cluster_state == "present"


    # Create Persistent Disk
    - name: Create Compute disk
      gcp_compute_disk:
        auth_kind: "{{gcp_auth_kind}}"
        service_account_file: "{{ gcp_service_account_file }}"
        scopes: "{{gcp_scopes}}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        name: "{{ persistent_disk_name }}"
        size_gb: "{{ persistent_disk_size }}"
        state: present
      register: disk
      when: cluster_state == "present"

    # Create Compute Instance
    - name: Create instance
      gcp_compute_instance:
        name: "{{ machine_instance_name }}"
        machine_type: "{{ machine_type }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
                source_image: "projects/debian-cloud/global/images/family/debian-11"
                disk_size_gb: "{{ machine_disk_size }}"
          - auto_delete: false
            boot: false
            source: "{{ disk }}"
        network_interfaces:
          - access_configs:
              - name: "External NAT"
                type: "ONE_TO_ONE_NAT"
        tags:
          items:
            - http-server
            - https-server
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        state: "{{ cluster_state }}"
      register: instance

    # Remove Persistent Disk
    - name: Remove Compute disk
      gcp_compute_disk:
        auth_kind: "{{gcp_auth_kind}}"
        service_account_file: "{{ gcp_service_account_file }}"
        scopes: "{{gcp_scopes}}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        name: "{{ persistent_disk_name }}"
        size_gb: "{{ persistent_disk_size }}"
        state: absent
      register: disk
      when: cluster_state == "absent"

    - name: Wait for SSH to come up
      wait_for: host={{ instance.networkInterfaces[0].accessConfigs[0].natIP }} port=22 delay=10 timeout=240
      when: cluster_state == "present"

    - name: Add host to groupname
      add_host: hostname={{ instance.networkInterfaces[0].accessConfigs[0].natIP }} groupname=new_instances
      when: cluster_state == "present"
