networks:
    default:
        name: sales-mate-network
        external: true
services:
    rag-copilot-pipeline:
        image: rag-copilot-pipeline
        container_name: rag-copilot-pipeline
        volumes:
            - ${SECRETS_DIR_COPILOT}:/secrets
            - ./rag_copilot_pipeline:/app
        ports:
            - 8081:8081 # Expose the FastAPI port to host
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: "/secrets/gcp-key.json"
            GCP_PROJECT: "ac-215-436117"
            DEV: "0" # Change to 0 for running web server
        healthcheck:
            test: ["CMD", "curl", "-f", "http://rag-copilot-pipeline:8081/"]
            interval: 10s
            timeout: 5s
            retries: 8
            start_period: 5s
        depends_on:
            - chromadb
    sales-mate-api-service:
        image: sales-mate-api-service
        container_name: sales-mate-api-service
        volumes:
            - ${SECRETS_DIR_API}:/secrets
            - ./api_service:/app
        ports:
            - 9000:9000 # Expose the FastAPI port to host
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: "/secrets/llm-service-account.json"
            GCP_PROJECT: "project-id-3187519002330642642"
            DEV: "0" # Change to 0 for running web server
            FINETUNED_MODEL: "1" # Toggle for using finetuned model or not
        healthcheck:
            test: ["CMD", "curl", "-f", "http://sales-mate-api-service:9000/"]
            interval: 10s
            timeout: 5s
            retries: 8
            start_period: 5s
        depends_on:
            - rag-copilot-pipeline
    chromadb:
        image: chromadb/chroma:latest
        container_name: llm-rag-chromadb
        ports:
            - 8000:8000
        volumes:
            - ./rag_copilot_pipeline/docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE
            - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"] # This is not recommended for production environments.
