networks:
    default:
        name: llm-rag-network
        external: true
services:
    rag-copilot-pipeline:
        image: rag-copilot-pipeline
        container_name: rag-copilot-pipeline
        volumes:
            - ./rag-copilot-pipeline/secrets:/secrets
            - ./rag-copilot-pipeline:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
        depends_on:
            - chromadb
    chromadb:
        image: chromadb/chroma:latest
        container_name: llm-rag-chromadb
        ports:
            - 8000:8000
        volumes:
            - ./rag-copilot-pipeline/docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE
            - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"] # This is not recommended for production environments.
