networks:
    default:
        name: llm-rag-network
        external: true
services:
    rag-copilot-pipeline:
        image: rag-copilot-pipeline
        container_name: rag-copilot-pipeline
        volumes:
            - ./rag-copilot-pipeline/secrets:/secrets
            - ./rag-copilot-pipeline:/app
        ports:
            - 8081:8081 # Expose the FastAPI port to host
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: "/secrets/gcp-key.json"
            GCP_PROJECT: "ac-215-436117"
        entrypoint: ["/bin/bash", "-c", "pipenv run fastapi dev server.py --host 0.0.0.0 --port 8081 --reload"]
        # command: ["fastapi dev server.py --port 8081"]
        depends_on:
            - chromadb
    chromadb:
        image: chromadb/chroma:latest
        container_name: llm-rag-chromadb
        ports:
            - 8000:8000
        volumes:
            - ./rag-copilot-pipeline/docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE
            - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"] # This is not recommended for production environments.
