name: CI Multi-Container Test

on:
  push:
    branches:
      - "*"  # Triggers when code is pushed to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment (specifically Python 3.12)
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 2.1: Set PYTHONPATH to include the root directory (or src if relevant)
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV  # Adds current directory to PYTHONPATH

      # Step 2.2: Install dependencies for linting
      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint black

      # Step 3: Load Secrets for GCP Keys and validate json
      - name: Write Secret to JSON File
        env:
          GCP_KEY_COPILOT: ${{ secrets.GCP_KEY_COPILOT }}
          GCP_KEY_API: ${{ secrets.GCP_KEY_API }}
          GCP_KEY_FINETUNING: ${{ secrets.GCP_KEY_FINETUNING }}
        run: |
          mkdir -p src/rag_copilot_pipeline/secrets
          mkdir -p src/api_service/secrets
          mkdir -p src/finetuning_pipeline/secrets
          python -c "import os; open('src/rag_copilot_pipeline/secrets/gcp-key.json', 'w').write(os.getenv('GCP_KEY_COPILOT', ''))"
          python -c "import os; open('src/api_service/secrets/llm-service-account.json', 'w').write(os.getenv('GCP_KEY_API', ''))"
          python -c "import os; open('src/finetuning_pipeline/secrets/llm-service-account.json', 'w').write(os.getenv('GCP_KEY_FINETUNING', ''))"
          jq empty src/rag_copilot_pipeline/secrets/gcp-key.json
          jq empty src/api_service/secrets/llm-service-account.json
          jq empty src/finetuning_pipeline/secrets/llm-service-account.json

      # Step 4: Run linting (non-blocking)
      - name: Run flake8
        continue-on-error: true
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run pylint
        continue-on-error: true
        run: pylint src/

      - name: Check code formatting with black
        continue-on-error: true
        run: black --check .

      # Step 4: Run the Docker Test Script
      - name: Run Primary API Docker Tests
        run: |
          cd src
          export SECRETS_DIR_COPILOT="./rag_copilot_pipeline/secrets"
          export SECRETS_DIR_API="./api_service/secrets"
          export DEV = "2" # Run in production mode

          # Create the network if we don't have it yet
          docker network inspect sales-mate-network >/dev/null 2>&1 || docker network create sales-mate-network

          # Build the image based on the Dockerfile
          docker build -t rag-copilot-pipeline -f ./rag_copilot_pipeline/Dockerfile ./rag_copilot_pipeline/
          docker build -t sales-mate-api-service -f ./api_service/Dockerfile ./api_service/

          # Run docker compose targeting one container
          # docker compose run --rm --service-ports $TARGET_IMAGE

          # Run all containers
          docker compose up --build -d
          timeout 5m docker compose logs -f
          sleep 30s

          # Define the services to test
          services=("rag-copilot-pipeline")

          # Run pytest in each container
          for service in "${services[@]}"; do
            echo "Running tests in $service..."
            docker compose exec "$service" pipenv run pytest || {
              echo "Tests failed in $service. Aborting."
              docker compose down
              exit 1
            }
          done

          # Stop the containers after tests
          docker compose down

          echo "All tests passed!"

          cd ..

      # Step 5: Run the Docker Test Script for finetuning
      - name: Run Finetunning tests
        run: |
          cd src/finetuning_pipeline
          source docker-shell.sh "pipenv run pytest" || {
              echo "Tests failed. Aborting."
              # Stop all containers (assuming they were started earlier)
              docker ps -aq | xargs docker rm
              exit 1
            }

          echo "Stopping all containers..."
          docker ps -aq | xargs docker rm

          echo "All tests passed!"

          cd ..
